#!/usr/bin/env python3
"""Create inbound wikilinks for gbrain orphan pages via generated hub index pages."""

from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
import tempfile
from collections import defaultdict
from pathlib import Path

GBRAIN_DIR = Path(os.environ.get("GBRAIN_DIR", str(Path.home() / "gbrain"))).expanduser()
HUB = os.environ.get("GBRAIN_DEORPHAN_HUB", "hub-knowledge-center")
ROOT_INDEX = os.environ.get("GBRAIN_DEORPHAN_ROOT", "hub-orphan-index")
MAX_LINKS_PER_PAGE = int(os.environ.get("GBRAIN_DEORPHAN_PAGE_SIZE", "250"))
START = "<!-- gbrain-deorphan:start -->"
END = "<!-- gbrain-deorphan:end -->"


def run(cmd: list[str], *, input_text: str | None = None, timeout: int = 180) -> subprocess.CompletedProcess[str]:
    return subprocess.run(cmd, input=input_text, cwd=GBRAIN_DIR, capture_output=True, text=True, timeout=timeout)


def load_orphans() -> list[dict]:
    proc = run(["gbrain", "orphans", "--json"], timeout=120)
    if proc.returncode != 0:
        raise SystemExit(proc.stderr or proc.stdout or "gbrain orphans --json failed")
    payload = json.loads(proc.stdout or "{}")
    rows = payload.get("orphans") or []
    return [row for row in rows if isinstance(row, dict) and row.get("slug")]


def safe_name(value: str) -> str:
    out = re.sub(r"[^a-zA-Z0-9_-]+", "-", value.strip().lower()).strip("-")
    return out[:80] or "misc"


def group_key(slug: str, domain: str | None) -> str:
    if slug.startswith("code/"):
        parts = slug.split("/")
        return "code-" + safe_name(parts[1] if len(parts) > 1 else "misc")
    if slug.startswith("book-"):
        return "books"
    if slug.startswith("chat-archive"):
        return "chat-archives"
    if slug.startswith("session-"):
        return "sessions"
    if "/" in slug:
        return safe_name(slug.split("/", 1)[0])
    if domain and domain != slug:
        return safe_name(domain)
    return safe_name(slug.split("-", 1)[0])


def chunked(items: list[dict], size: int) -> list[list[dict]]:
    return [items[index : index + size] for index in range(0, len(items), size)]


def write_index_pages(out_dir: Path, orphans: list[dict]) -> list[str]:
    groups: dict[str, list[dict]] = defaultdict(list)
    for row in orphans:
        groups[group_key(str(row["slug"]), row.get("domain"))].append(row)

    index_slugs = []
    for key, rows in sorted(groups.items()):
        chunks = chunked(sorted(rows, key=lambda item: item["slug"]), MAX_LINKS_PER_PAGE)
        for part, batch in enumerate(chunks, start=1):
            index_slug = f"hub-orphans-{key}" if len(chunks) == 1 else f"hub-orphans-{key}-{part:02d}"
            index_slugs.append(index_slug)
            page = out_dir / f"{index_slug}.md"
            lines = [
                "---",
                "type: hub",
                f"title: Orphan Index - {key}",
                "tags:",
                "  - hub",
                "  - maintenance",
                "  - orphan-index",
                "---",
                "",
                f"# Orphan Index - {key}",
                "",
                "Generated by gbrain_deorphan_index.py. These links keep otherwise isolated pages reachable.",
                "",
            ]
            for row in batch:
                title = str(row.get("title") or row["slug"]).replace("\n", " ").strip()
                slug = str(row["slug"])
                lines.append(f"- [[{slug}]] - {title}")
            page.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    return index_slugs


def update_root_hub(index_slugs: list[str]) -> None:
    proc = run(["gbrain", "get", HUB], timeout=60)
    current = proc.stdout if proc.returncode == 0 and proc.stdout.strip() else f"# {HUB}\n"
    block_lines = [START, "", "## Generated Orphan Indexes", ""]
    for slug in sorted(index_slugs):
        block_lines.append(f"- [[{slug}]]")
    block_lines.extend(["", END])
    block = "\n".join(block_lines)
    if START in current and END in current:
        current = re.sub(re.escape(START) + r".*?" + re.escape(END), block, current, flags=re.S)
    else:
        current = current.rstrip() + "\n\n" + block + "\n"
    proc = run(["gbrain", "put", HUB], input_text=current, timeout=120)
    if proc.returncode != 0:
        raise SystemExit(proc.stderr or proc.stdout or f"gbrain put {HUB} failed")


def main() -> int:
    orphans = load_orphans()
    filtered = [
        row
        for row in orphans
        if not str(row["slug"]).startswith("hub-orphans-") and row["slug"] != ROOT_INDEX
    ]
    print(f"Orphans reported: {len(orphans)}")
    print(f"Orphans to index: {len(filtered)}")
    if not filtered:
        return 0

    tmp = Path(tempfile.mkdtemp(prefix="gbrain-deorphan-index-"))
    try:
        index_slugs = write_index_pages(tmp, filtered)
        root_page = tmp / f"{ROOT_INDEX}.md"
        root_page.write_text(
            "\n".join(
                [
                    "---",
                    "type: hub",
                    "title: Orphan Index Root",
                    "tags:",
                    "  - hub",
                    "  - maintenance",
                    "  - orphan-index",
                    "---",
                    "",
                    "# Orphan Index Root",
                    "",
                    *[f"- [[{slug}]]" for slug in sorted(index_slugs)],
                ]
            )
            + "\n",
            encoding="utf-8",
        )
        index_slugs.append(ROOT_INDEX)
        update_root_hub(index_slugs)

        proc = run(["gbrain", "import", str(tmp), "--no-embed", "--workers", "8"], timeout=600)
        print(proc.stdout.strip())
        if proc.returncode != 0:
            raise SystemExit(proc.stderr or "gbrain import failed")

        proc = run(["gbrain", "extract", "links", "--source", "db", "--include-frontmatter"], timeout=600)
        print(proc.stdout.strip())
        if proc.returncode != 0:
            raise SystemExit(proc.stderr or "gbrain extract links failed")

        health = run(["gbrain", "health"], timeout=120)
        print("=== FINAL ===")
        print(health.stdout.strip())
        return health.returncode
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


if __name__ == "__main__":
    raise SystemExit(main())
